### PR TITLE
Fix: Unsafe working directory due to latest Git security vulnerability fix

### LINKED ISSUE #8: Fix: Unsafe working directory due to latest Git security vulnerability fix
## Issue

On the latest version of the Git runner, due to a security patch, we no longer can initialize sub git repositories via the runner due to security permissions 
https://github.blog/2022-04-12-git-security-vulnerability-announced/

Screen Shot 2022-06-15 at 11 21 34 AM

More details on the issue here https://github.com/actions/checkout/issues/760

## Expected

Wiki should properly initialize the sub-repo and push the changes to the wiki repository

Simply adding the following to the `entrypoint.sh` should resolve the issue

```sh
# Add Safe Directory to initialize sub repo
git config --global --add safe.directory "/github/workspace"
git config --global --add safe.directory "/github/workspace/$TEMP_CLONE_WIKI_FOLDER"
```
 
## Steps to reproduce

1. Use the latest version of the Publish Github Wiki Action
2. Attempt to publish the wiki following the usage instructions
3. Observe the error in the Publish Wiki step

### PR DESCRIPTION
**Pull request by bterone**
Closes #8 

## What happened

✅ Mark the temp wiki directory as safe and can successfully initialize the sub repo

## Insight

More insight in the issue https://github.com/nimblehq/publish-github-wiki-action/issues/8 📖 

Following the instructions in the error, we're forced to mark the temp wiki folder where we initialize git to be a safe directory
This is due to the latest changes in git https://github.blog/2022-04-12-git-security-vulnerability-announced/  📰 
 
## Proof Of Work

After testing on another repo the fix in https://github.com/nimblehq/publish-github-wiki-action/releases/tag/v0.1.0-alpha-4
It successfully pushes to the wiki

Screen Shot 2022-10-28 at 3 41 05 PM

### CODE REVIEW

**Review by toby-thanathip — APPROVED** [review]

File: entrypoint.sh [hunk 1]
```diff
@@ -41,6 +41,11 @@ add_mask "${USER_ACCESS_TOKEN}"
 {
   mkdir $TEMP_CLONE_WIKI_FOLDER
   cd $TEMP_CLONE_WIKI_FOLDER || exit 1
+
+  # Add Safe Directory to initialize sub repo
+  git config --global --add safe.directory "/github/workspace"
```
Comment (toby-thanathip) [inline entrypoint.sh:46]: Just wondering, is this line necessary? 🙏

Comment (bterone) [reply entrypoint.sh:46]: Ah, I'll create a chore to investigate if this is necessary 👍
